author: SwearWord
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: org.getchunky.chunkyvillage.ChunkyVillage
name: ChunkyVillage
startup: postworld
url: http://getchunky.org/
version: ${build.number}
commands:
    town:
        description: The root command for town stuff.
        aliases: t
permissions:
    chunky.town.create:
        description: Create new towns.
        default: op
    chunky.admin.teleport:
        description: Teleport without restrictions.
        default: op
